### ISSUE TITLE
Empty "material" pages

### ISSUE THREAD

**Issue by arokem** [weecology/forecasting-course#21]
For example, [this page](https://course.naturecast.org/lessons/intro-time-series-data/material/) looks like this: 

<img width="1624" alt="Screenshot 2023-03-13 at 5 07 08 PM" src="https://user-images.githubusercontent.com/118582/224858857-6a43f9e6-319d-41d2-a7c7-091a16a496da.png">

**Comment by ethanwhite** [comment]
Thanks for flagging this @arokem. All of the empty pages should now be removed via #28.
